version: '2'
services:
### NGINX Server Container ##################################

    nginx:
      image: bigrocs/nginx:latest
      volumes:
        - ./logs/nginx/:/var/log/nginx
        - ./nginx/sites/:/etc/nginx/sites-available
        - ./nginx/nginx.conf/:/etc/nginx/nginx.conf
        - ./nginx/conf.d/upstream.conf/:/etc/nginx/conf.d/upstream.conf
        - ./wwwroot:/var/www
      ports:
        - "80:80"
        - "443:443"
### Volumes Setup #############################################

# volumes:
#   mysql:
#     driver: "local"
