version: '2'
services:
### NGINX Server Container ##################################

    nginx:
      image: bigrocs/nginx:latest
      volumes:
        - /www/logs/nginx:/var/log/nginx
        - /www/nginx/sites:/etc/nginx/sites-available
        - /www/nginx/nginx.conf:/etc/nginx/nginx.conf
        - /www/nginx/conf.d/upstream.conf:/etc/nginx/conf.d/upstream.conf
        - /www/wwwroot:/var/www
      ports:
        - "80:80"
        - "443:443"
### Volumes Setup #############################################

    volumes:
      sshvolume:
        driver: " vieux/sshfs"
        driver_opts:
          sshcmd: root@172.16.84.200:/www
          password: 001pengjie
