version: '2'
services:
### NGINX Server Container ##################################

    nginx:
      image: bigrocs/nginx:latest
      volumes:
        - sshvolume/logs/nginx/:/var/log/nginx
        - sshvolume/nginx/sites/:/etc/nginx/sites-available
        - sshvolume/nginx/nginx.conf/:/etc/nginx/nginx.conf
        - sshvolume/nginx/conf.d/upstream.conf/:/etc/nginx/conf.d/upstream.conf
        - sshvolume/wwwroot:/var/www
      ports:
        - "80:80"
        - "443:443"
### Volumes Setup #############################################

# volumes:
#   mysql:
#     driver: "local"
